#!/bin/bash
#
# Install this custom .vim directory on a fresh machine
#

# First step is to run this command to clone the repo:
# git clone git@github.com:stevenocchipinti/dotvim.git ~/.vim

# Next, get Vundle to manage plugins
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# Backup the originals (if they're not there, don't complain)
[ -f ~/.vimrc ]  && mv -i ~/.vimrc{,.bak}
[ -f ~/.gvimrc ] && mv -i ~/.gvimrc{,.bak}

# Symlink version controlled files to the home directory
ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc

# Install all the plugins
vim +BundleInstall +qall
