#!/bin/bash
#
# Install this custom .vim directory on a fresh machine
#

# First step is to run this command to clone the repo:
# git clone git@github.com:stevenocchipinti/dotvim.git ~/.vim

# Backup the originals (if they're not there, don't complain)
[ -f ~/.vimrc ]  && mv -i ~/.vimrc{,.bak}
[ -f ~/.gvimrc ] && mv -i ~/.gvimrc{,.bak}

ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc

cd ~/.vim
git submodule update --init
