#!/bin/bash
#
# Install this custom .vim directory on a fresh machine
#

if [ -d ~/.vim ]; then
  echo "You already have a .vim directory!"
  exit 1
fi

git clone git@github.com:stevenocchipinti/dotvim.git ~/.vim

# Backup the originals (if they're not there, don't complain)
[ -f ~/.vim/vimrc ]  && mv -i ~/.vim/vimrc{,.bak}
[ -f ~/.vim/gvimrc ] && mv -i ~/.vim/gvimrc{,.bak}

ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc

cd ~/.vim
git submodule update --init
